# Generated by Django 5.2.5 on 2025-10-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldUser',
        ),
    ]
