# Generated by Django 5.2.5 on 2025-10-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_olduser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
